name: tumitate_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2
  cupertino_icons: ^1.0.6
  decimal: ^2.3.3
  dio: ^5.4.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - lib/core/assets/img/
    - lib/core/assets/img/flg/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/core/assets/img/launcher_icon.png"
  min_sdk_android: 21
